### ISSUE TITLE
Incorrect mask example

### ISSUE THREAD

**Issue by caroig** [vasile/Mask-KML-polygons#1]
$ xsltproc --stringparam mask '-25,15 40,15 40,80 -25,80 -25,15' cantons.kml > cantons_inverted.kml  

should be

$ xsltproc --stringparam mask '-25,15 40,15 40,80 -25,80 -25,15' invert.xsl cantons.kml > cantons_inverted.kml

Great tool, thanks.

**Comment by vasile** [comment]
(y) thanks for reporting, the README is updated
