### ISSUE TITLE
How did you generate the cantons.kml?

### ISSUE THREAD

**Issue by VanCoding** [vasile/Mask-KML-polygons#2]
Could you maybe explain somewhere how you generated the cantons.kml from the GG25 data?

I want to get polygons of cantons, local authorities, counties for displaying on a google map, but in the GG25 data, only the kmz file is lat/long based and it does not contain polygons. Just lines with no relations to each other.

It would be cool if you could let me know about how you processed the data :)

**Comment by vasile** [comment]
In the archive you get a shp folder containing the ESRI Shapefiles of the geometries. These you can visualize with tools like Quantum GIS and export the data as KML or GeoJSON file
