### ISSUE TITLE
Result of inversion is wrong

### ISSUE THREAD

**Issue by guibar** [vasile/Mask-KML-polygons#3]
Hello,
I have tried inverting a kml file with the boundary of the city of Toronto that was generated using ArcMap and the result I get is clearly wrong. When looked at in Google earth it defines a much larger area somewhere in western Europe. Unfortunately, it doesn't look as if I can submit the kml file here.

**Comment by vasile** [comment]
Hello @guibar , you can mail it here http://www.vasile.ch/contact.html

**Comment by guibar** [comment]
Hi Vasile,

Sorry, you can close my issue, I had misunderstood what was supposed to
happen. I thought the outermost borders where meant to have sensible
default values. I know understood what I have to do to get the desired
results.

Thanks a lot!

Guillaume

**Comment by vasile** [comment]
No worries @guibar - have a look also at https://github.com/vasile/geomask - it's a masking alternative, done client-side
